flowchart LR
    orbit[Orbit] --> propagation[Propagation]
    propagation --> coordinate[Coordinate Transform \n ECI -> ECEF]
    coordinate --> location[Location ECEF]
    location --> lineofsight[Line of Sight Vector]
    lineofsight --> algorithm[Pass Finding Algorithm]
    time[time, t] -->  